Webshop/Controllers/BasketController.cs
using AutoMapper;
using Core.Dtos;
using Core.Entities.BasketModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Webshop.Shared;

namespace Webshop.Controllers
{
    public class BasketController : Controller
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IMapper _mapper;

        public BasketController(IHttpContextAccessor httpContextAccessor, IMapper mapper)
        {

            _httpContextAccessor = httpContextAccessor;
            _mapper = mapper;
        }

        public async Task<Tuple<object, object, object,object>> PublicMethods()
        {
            var service = new SharedSpace(_httpContextAccessor,_mapper);
            TempData["types"] = await service.FetchProductTypes();
            TempData["brands"] = await service.FetchProducBrands();
            var basketProducts = await service.FetchBasket();
            TempData["basketItems"] = basketProducts.Items.Count;
            decimal total = 0;
            foreach (var pro in basketProducts.Items)
            {
                total = total + (pro.Price * pro.Quantity);
                TempData["total"] = total;
            }
            return Tuple.Create(TempData["types"], TempData["brands"], TempData["basketItems"], TempData["total"]);
        }


        public async Task<IActionResult> Index()
        {
            var service = new SharedSpace(_httpContextAccessor,_mapper);
            var result = await service.FetchBasket();
            await PublicMethods();           
            return View(result);
        }

        public async Task<IActionResult> AddToBasket(ProductToReturnDto product)
        {         
            var service = new SharedSpace(_httpContextAccessor,_mapper);
            await service.AddProductToBasket(product);          
            return RedirectToAction("Index", "Products");
        }

        public async Task<IActionResult> RemoveItem(int id)
        {
            var service = new SharedSpace(_httpContextAccessor,_mapper);
            var result = await service.FetchBasket();
            var item = result.Items.Where(x => x.Id == id).FirstOrDefault();
            result.Items.Remove(item);
            var customerBasket = _mapper.Map<CustomerBasket, CustomerBasketDto>(result);
            await service.UpdateBasketMVC(customerBasket);
            await PublicMethods();            
            return View("Index",result);
        }

        public async Task<IActionResult> IncrementItemQuantity(int id)
        {
            var service = new SharedSpace(_httpContextAccessor,_mapper);
            var result = await service.FetchBasket();
            var item = result.Items.FindIndex(x => x.Id == id);
            result.Items[item].Quantity++;
            var customerBasket = _mapper.Map<CustomerBasket, CustomerBasketDto>(result);
            await service.UpdateBasketMVC(customerBasket);
            await PublicMethods();           
            return View("Index",result);
        }

        public async Task<IActionResult> DecrementItemQuantity(int id)
        {
            var service = new SharedSpace(_httpContextAccessor,_mapper);
            var result = await service.FetchBasket();
            var item = result.Items.FindIndex(x => x.Id == id);
            if (result.Items[item].Quantity > 1)
            {
                result.Items[item].Quantity--;
                var customerBasket = _mapper.Map<CustomerBasket, CustomerBasketDto>(result);
                await service.UpdateBasketMVC(customerBasket);
                await PublicMethods();              
                return View("Index", result);
            }
            else
            {
               return await RemoveItem(id);              
            }           
        }
    }
}

Webshop/Controllers/CheckoutController.cs
using AutoMapper;
using Core.Dtos;
using Core.Entities.BasketModels;
using Core.Entities.OrderModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Webshop.Models.ViewModels;
using Webshop.Shared;

namespace Webshop.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IMapper _mapper;
      
        public CheckoutController(IHttpContextAccessor httpContextAccessor, IMapper mapper)
        {
            _httpContextAccessor = httpContextAccessor;
            _mapper = mapper;
        }

        public async Task<Tuple<object, object, object, object>> PublicMethods()
        {           
           
            var service = new SharedSpace(_httpContextAccessor,_mapper);
            TempData["types"] = await service.FetchProductTypes();
            TempData["brands"] = await service.FetchProducBrands();
            var basketProducts = await service.FetchBasket();
            TempData["basketItems"] = basketProducts.Items.Count;
            decimal total = 0;
            foreach (var pro in basketProducts.Items)
            {
                total = total + (pro.Price * pro.Quantity);
                TempData["total"] = total;
            }
            return Tuple.Create(TempData["types"], TempData["brands"], TempData["basketItems"], TempData["total"]);
        }

        public async Task<IActionResult> GetAllOrdersForUser()
        {
            var token = _httpContextAccessor.HttpContext.Session.GetString("JWToken");
            var basketId = _httpContextAccessor.HttpContext.Session.GetString("basketId");

            if (token == null || token == "")
            {
                TempData["NotLoggedin"] = "You must loggedIn ...";
                return RedirectToAction("Index", "Account");
            }

            var result = new List<OrderToReturnDto>();

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                using (var response = await httpClient.GetAsync("https://localhost:5001/api/orders/getorders"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    result = JsonConvert.DeserializeObject<List<OrderToReturnDto>>(apiResponse);
                }
            }
            await PublicMethods();
            return View("AllOrders", result);
        }


        [ResponseCache(Location = ResponseCacheLocation.None, Duration = 0, VaryByHeader = "None", NoStore = true)]
        public async Task<IActionResult> CheckoutBasket()
        {
            var token = _httpContextAccessor.HttpContext.Session.GetString("JWToken");
            var basketId = _httpContextAccessor.HttpContext.Session.GetString("basketId");
            var email = _httpContextAccessor.HttpContext.Session.GetString("Email");

            if (token == null || token == "")
            {
                TempData["NotLoggedin"] = "You must loggedIn ...";
                return RedirectToAction("Index", "Account");
            }

            Address address = new Address();
            var deliveryMethods = new List<DeliveryMethod>();
            var myModel = new Basket_Order_vm();
            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                using (var response = await httpClient.GetAsync("https://localhost:5001/api/account/address"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    address = JsonConvert.DeserializeObject<Address>(apiResponse);
                }
            }
            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                using (var response = await httpClient.GetAsync("https://localhost:5001/api/orders/deliverymethods"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    deliveryMethods = JsonConvert.DeserializeObject<List<DeliveryMethod>>(apiResponse);
                    ViewData["methods"] = deliveryMethods;
                }
            }

            var service = new SharedSpace(_httpContextAccessor,_mapper);
            var myBasket = await service.FetchBasket();

            myModel.customerBasketDto = _mapper.Map<CustomerBasket, CustomerBasketDto>(myBasket);
            myModel.OrderToReturnDto.ShipToAddress = new Address(address.FirstName, address.LastName, address.Street, address.City, address.State, address.Zipcode);
            myModel.OrderToReturnDto.DeliveryMethod = myBasket.DeliveryMethodId.ToString();
            myModel.OrderToReturnDto.OrderDate = DateTimeOffset.Now;
            myModel.OrderToReturnDto.Status = OrderStatus.Pending.ToString();
            myModel.OrderToReturnDto.BuyerEmail = email;

            decimal subTotal = 0;

            foreach (var item in myBasket.Items)
            {
                subTotal += item.Price * item.Quantity;
            }
            myModel.OrderToReturnDto.Subtotal = subTotal;
            myModel.OrderToReturnDto.ShippingPrice = 0;
            myModel.OrderToReturnDto.Total = subTotal + myModel.OrderToReturnDto.ShippingPrice;

            await PublicMethods();
            return View("Index", myModel);
        }


        [HttpPost]       
        [ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, Duration = 0, VaryByHeader = "None", NoStore = true)]
        public async Task<IActionResult> CreateOrderMVC(OrderDto input)
        {
            _httpContextAccessor.HttpContext.Session.SetString("deliveryId",input.DeliveryMethodId.ToString());
            var service = new SharedSpace(_httpContextAccessor,_mapper);
            var createdModel = await service.CreateOrderMVC(input);
            var model = _mapper.Map<Order, OrderToReturnDto>(createdModel);         
            model.Total = createdModel.GetTotal();
            await PublicMethods();
            if (createdModel.Id == 0)
            {
                return Redirect("https://localhost:44325/");
            }
           
            return View("Payment", model);          
        }
    }
}

Webshop/Views/Basket/Index.cshtml
@{
    Layout = "_Layout";
}
@using Core.Dtos;
@model Core.Entities.BasketModels.CustomerBasket;
@{ 
    decimal total = 0;
    decimal subtotal = 0;
    decimal allTotal = 0;
}

<br />
<p class="lead"><h1>Basket</h1></p>
<div class="container mt-2">
    <div>
        @if (Model.Items.Count == 0)
        {
          <p>There are no items in your basket</p>
        }
    </div>

    <div>
        <div class="pb-5">
            <div class="container">
                <div class="row">
                    <div class="col-12 py-5 mb-1">
                        <div class="table-responsive">
                            <table class="table table-borderless">
                                <thead class="border-0 py-2">
                                    <tr>
                                        <th scope="col">
                                            <div class="p-2 px-3 text-uppercase">Product</div>
                                        </th>
                                        <th scope="col">
                                            <div class="py-2 text-uppercase">Price</div>
                                        </th>
                                        <th scope="col">
                                            <div class="py-2 text-uppercase">Quantity</div>
                                        </th>
                                        <th scope="col">
                                            <div class="py-2 text-uppercase">Total</div>
                                        </th>
                                        <th scope="col" class="border-0">
                                            <div class="py-2 text-uppercase">&nbsp;&nbsp;&nbsp;&nbsp;Remove</div>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.Items)
                                    {
                                        <tr class="border-0">
                                            <th scope="row">
                                                <div class="p-0">
                                                    <img src="@item.PictureUrl" alt="@item.ProductName"
                                                         class="img-fluid" style="max-height: 50px;">
                                                    <div class="ml-3 d-inline-block align-middle">
                                                        <h5 class="mb-0">
                                                            <a class="text-dark">@item.ProductName</a>
                                                        </h5>
                                                        <span class="text-muted font-weight-normal font-italic d-block">
                                                            Type: @item.Type
                                                        </span>
                                                    </div>
                                                </div>
                                            </th>
                                            <td class="align-middle"><strong> @String.Format("{0:c2}", item.Price)</strong></td>
                                            <td class="align-middle">
                                                <div class="d-flex align-items-center">
                                                    <a asp-controller="Basket" asp-action="DecrementItemQuantity" asp-route-id="@item.Id">
                                                        <i class="fa fa-minus-circle text-warning mr-2"
                                                           style="cursor: pointer; font-size: 2em;">
                                                        </i>
                                                        </a>

                                                        <span class="font-weight-bold" style="font-size: 1.5em;">
                                                            @item.Quantity
                                                        </span>
                                                        <a asp-controller="Basket" asp-action="IncrementItemQuantity" asp-route-id="@item.Id">
                                                            <i class="fa fa-plus-circle text-warning mx-2"
                                                               style="cursor: pointer; font-size: 2em;"></i>
                                                        </a>
                                                </div>
                                            </td>
                                            <td class="align-middle">
                                                @{  total = item.Price * item.Quantity;}
                                                <strong>@String.Format("{0:c2}", total)</strong>
                                            </td>
                                            <td class="align-middle text-center">
                                                <a class="text-danger" asp-controller="Basket" asp-action="RemoveItem" asp-route-id="@item.Id">                                                
                                                    <i class="fa fa-trash" style="font-size: 2em; cursor: pointer;"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="bg-light px-4 text-uppercase font-weight-bold" style="padding: 1.20em;">
                        Order Summary
                    </div>
                    <div class="p-4">
                        <p class="font-italic mb-4">Shipping costs will be added depending on choices made during checkout</p>
                        <ul class="list-unstyled mb-4">
                            <li class="d-flex justify-content-between py-3 border-bottom">
                                <strong class="text-muted">Order subtotal</strong>
                                @{                                    
                                    foreach (var pro in Model.Items)
                                    {
                                        subtotal = subtotal + pro.Price;
                                        allTotal = subtotal;
                                    }
                                }
                                <strong>@String.Format("{0:c2}", TempData["total"])</strong>
                            </li>
                            <li class="d-flex justify-content-between py-3 border-bottom">
                                <strong class="text-muted">Shipping and handling</strong>
                                <strong>@String.Format("{0:c2}", 0)</strong>
                            </li>
                            <li class="d-flex justify-content-between py-3 border-bottom">
                                <strong class="text-muted">Total</strong>
                                <strong>@String.Format("{0:c2}", TempData["total"])</strong>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            @if (Model.Items.Count != 0)
            {
            <div class="col-6 offset-6">
                <a class="btn btn-outline-primary py-2 btn-block" asp-controller="Checkout" asp-action="CheckoutBasket">
                    Proceed to checkout
                </a>
            </div>
            }
        </div>
    </div>
</div>